"""empty message

Revision ID: 041491258676
Revises: 4ce200c6ceb7
Create Date: 2018-12-20 12:28:24.066477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '041491258676'
down_revision = '4ce200c6ceb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inheritmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('has_penis', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tests', sa.Column('person_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'person_type')
    op.drop_table('inheritmodel')
    # ### end Alembic commands ###
