"""empty message

Revision ID: 0a0c5c092b11
Revises: 8fcd1b58a2a3
Create Date: 2018-12-26 17:02:35.119216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0c5c092b11'
down_revision = '8fcd1b58a2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('cow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'cows', ['cow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'cow_id')
    # ### end Alembic commands ###
