"""empty message

Revision ID: 0c99067ee659
Revises: 7339882155b4
Create Date: 2018-12-25 06:58:31.163357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c99067ee659'
down_revision = '7339882155b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inheritmodel', 'date_cured')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inheritmodel', sa.Column('date_cured', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
