"""empty message

Revision ID: 1247dcf00939
Revises: 
Create Date: 2019-01-02 12:33:45.242670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1247dcf00939'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=20), nullable=True),
    sa.Column('private_id', sa.String(length=10), nullable=True),
    sa.Column('current_pen', sa.String(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pub_id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=20), nullable=True),
    sa.Column('date_started', sa.BigInteger(), nullable=True),
    sa.Column('date_stopped', sa.BigInteger(), nullable=True),
    sa.Column('medication_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_diagnosed', sa.BigInteger(), nullable=True),
    sa.Column('date_treated', sa.BigInteger(), nullable=True),
    sa.Column('date_cured', sa.BigInteger(), nullable=True),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('pub_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pub_id'], ['cows.pub_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastitis',
    sa.Column('is_right_front_affected', sa.Boolean(), nullable=True),
    sa.Column('is_left_front_affected', sa.Boolean(), nullable=True),
    sa.Column('is_right_back_affected', sa.Boolean(), nullable=True),
    sa.Column('is_left_back_affected', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastitis_medications',
    sa.Column('mastitis_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['mastitis_id'], ['mastitis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastitis_medications')
    op.drop_table('mastitis')
    op.drop_table('problems')
    op.drop_table('users')
    op.drop_table('medications')
    op.drop_table('cows')
    # ### end Alembic commands ###
