"""empty message

Revision ID: 250613310661
Revises: 
Create Date: 2018-12-28 21:14:53.148918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250613310661'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=20), nullable=True),
    sa.Column('private_id', sa.String(length=10), nullable=True),
    sa.Column('current_pen', sa.String(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_diagnosed', sa.BigInteger(), nullable=True),
    sa.Column('date_treated', sa.BigInteger(), nullable=True),
    sa.Column('date_cured', sa.BigInteger(), nullable=True),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mastitis',
    sa.Column('is_right_front_affected', sa.Boolean(), nullable=True),
    sa.Column('is_left_front_affected', sa.Boolean(), nullable=True),
    sa.Column('is_right_back_affected', sa.Boolean(), nullable=True),
    sa.Column('is_left_back_affected', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mastitis')
    op.drop_table('problems')
    op.drop_table('users')
    op.drop_table('cows')
    # ### end Alembic commands ###
