"""empty message

Revision ID: 462f2ecdace2
Revises: 92b85f9cbf5e
Create Date: 2018-12-25 22:47:48.776667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462f2ecdace2'
down_revision = '92b85f9cbf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('date_treated', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'date_treated')
    # ### end Alembic commands ###
