"""empty message

Revision ID: 4ce200c6ceb7
Revises: 84920be29dcd
Create Date: 2018-12-20 10:41:26.207190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce200c6ceb7'
down_revision = '84920be29dcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('is_real', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'is_real')
    # ### end Alembic commands ###
