"""empty message

Revision ID: 515cd21af8a5
Revises: 75b7d35458a4
Create Date: 2018-12-21 21:27:59.547144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515cd21af8a5'
down_revision = '75b7d35458a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_diagnosed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_treated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_cured', sa.DateTime(timezone=True), nullable=True),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
