"""empty message

Revision ID: 7339882155b4
Revises: 069b313dbb7c
Create Date: 2018-12-25 01:02:53.624308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7339882155b4'
down_revision = '069b313dbb7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inheritmodel', sa.Column('date_cured', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inheritmodel', 'date_cured')
    # ### end Alembic commands ###
