"""empty message

Revision ID: 75b7d35458a4
Revises: 
Create Date: 2018-12-20 19:55:44.492137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b7d35458a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=20), nullable=True),
    sa.Column('private_id', sa.String(length=10), nullable=True),
    sa.Column('current_pen', sa.String(), nullable=True),
    sa.Column('mother_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('is_real', sa.Boolean(), nullable=True),
    sa.Column('person_type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inheritmodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('has_penis', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inheritmodel')
    op.drop_table('users')
    op.drop_table('tests')
    op.drop_table('cows')
    # ### end Alembic commands ###
