"""empty message

Revision ID: 7815a83a759b
Revises: cdad8be12561
Create Date: 2018-12-25 00:12:41.181152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7815a83a759b'
down_revision = 'cdad8be12561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_diagnosed', sa.BigInteger(), nullable=True),
    sa.Column('date_treated', sa.BigInteger(), nullable=True),
    sa.Column('date_cured', sa.BigInteger(), nullable=True),
    sa.Column('problem_type', sa.String(length=32), nullable=False),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems')
    # ### end Alembic commands ###
