"""empty message

Revision ID: 7b3c1f42ca28
Revises: d6dc51e4537b
Create Date: 2018-12-26 16:39:42.384665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3c1f42ca28'
down_revision = 'd6dc51e4537b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('cow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tests', 'cows', ['cow_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'cow_id')
    # ### end Alembic commands ###
