"""empty message

Revision ID: 84920be29dcd
Revises: a617e00bf6e5
Create Date: 2018-12-20 10:23:40.584995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84920be29dcd'
down_revision = 'a617e00bf6e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
