"""empty message

Revision ID: 8fcd1b58a2a3
Revises: 7b3c1f42ca28
Create Date: 2018-12-26 16:52:59.471485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcd1b58a2a3'
down_revision = '7b3c1f42ca28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tests_cow_id_fkey', 'tests', type_='foreignkey')
    op.drop_column('tests', 'cow_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('cow_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tests_cow_id_fkey', 'tests', 'cows', ['cow_id'], ['id'])
    # ### end Alembic commands ###
