"""empty message

Revision ID: 92b85f9cbf5e
Revises: 0c99067ee659
Create Date: 2018-12-25 22:29:53.773292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b85f9cbf5e'
down_revision = '0c99067ee659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inheritmodel', 'date_diagnosed')
    op.add_column('tests', sa.Column('date_cured', sa.BigInteger(), nullable=True))
    op.add_column('tests', sa.Column('date_diagnosed', sa.BigInteger(), nullable=True))
    op.add_column('tests', sa.Column('problem_type', sa.String(length=30), nullable=True))
    op.drop_column('tests', 'is_real')
    op.drop_column('tests', 'person_type')
    op.drop_column('tests', 'age')
    op.drop_column('tests', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('person_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('is_real', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tests', 'problem_type')
    op.drop_column('tests', 'date_diagnosed')
    op.drop_column('tests', 'date_cured')
    op.add_column('inheritmodel', sa.Column('date_diagnosed', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
