"""empty message

Revision ID: 94f8de6db596
Revises: 
Create Date: 2018-08-04 19:45:24.656093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f8de6db596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cowrelationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_private_id', sa.String(), nullable=True),
    sa.Column('child_private_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub_id', sa.String(length=20), nullable=True),
    sa.Column('private_id', sa.String(length=10), nullable=True),
    sa.Column('heredity', sa.String(length=10), nullable=True),
    sa.Column('type_of_delivery', sa.String(), nullable=True),
    sa.Column('current_pen', sa.String(), nullable=True),
    sa.Column('cow_relationship_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_relationship_id'], ['cowrelationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sickness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=20), nullable=True),
    sa.Column('date_diagnosed', sa.Integer(), nullable=True),
    sa.Column('is_cured', sa.Boolean(), nullable=True),
    sa.Column('cure_date', sa.Integer(), nullable=True),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccine_name', sa.String(length=20), nullable=True),
    sa.Column('date_given', sa.Integer(), nullable=True),
    sa.Column('cow_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cow_id'], ['cows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=20), nullable=True),
    sa.Column('date_given', sa.Integer(), nullable=True),
    sa.Column('sickness_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sickness_id'], ['sickness.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medications')
    op.drop_table('vaccines')
    op.drop_table('sickness')
    op.drop_table('cows')
    op.drop_table('cowrelationships')
    # ### end Alembic commands ###
