"""empty message

Revision ID: a617e00bf6e5
Revises: e9e1cc15946e
Create Date: 2018-12-20 10:02:19.520843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a617e00bf6e5'
down_revision = 'e9e1cc15946e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mastitis_id_fkey', 'mastitis', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('mastitis_id_fkey', 'mastitis', 'problems', ['id'], ['id'])
    # ### end Alembic commands ###
