"""empty message

Revision ID: b7ec54e10c06
Revises: b9d0bd0d51ed
Create Date: 2018-12-16 20:03:22.948743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ec54e10c06'
down_revision = 'b9d0bd0d51ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cows', sa.Column('current_pen', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cows', 'current_pen')
    # ### end Alembic commands ###
