"""empty message

Revision ID: b9d0bd0d51ed
Revises: 29050e4acbd8
Create Date: 2018-12-16 20:03:11.519025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9d0bd0d51ed'
down_revision = '29050e4acbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cows', 'current_pen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cows', sa.Column('current_pen', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
