"""empty message

Revision ID: e9e1cc15946e
Revises: b7ec54e10c06
Create Date: 2018-12-20 08:23:48.164647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e9e1cc15946e'
down_revision = 'b7ec54e10c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'date_cured')
    op.drop_column('problems', 'date_diagnosed')
    op.drop_column('problems', 'date_treated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('date_treated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('date_diagnosed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('date_cured', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
