"""empty message

Revision ID: fe548c25b628
Revises: 0a0c5c092b11
Create Date: 2018-12-26 18:43:26.127218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe548c25b628'
down_revision = '0a0c5c092b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inheritmodel', sa.Column('cow_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'inheritmodel', 'cows', ['cow_id'], ['id'])
    op.drop_column('inheritmodel', 'has_penis')
    op.drop_constraint('tests_cow_id_fkey', 'tests', type_='foreignkey')
    op.drop_column('tests', 'cow_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('cow_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tests_cow_id_fkey', 'tests', 'cows', ['cow_id'], ['id'])
    op.add_column('inheritmodel', sa.Column('has_penis', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inheritmodel', type_='foreignkey')
    op.drop_column('inheritmodel', 'cow_id')
    # ### end Alembic commands ###
